version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db_v5
    env_file: ".env"
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB" ]
      interval: 5s
      retries: 5
      timeout: 3s

  app:
    build: .
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    env_file: ".env"
    volumes:
      - .:/app
    ports:
      - "8002:8000"

volumes:
  db_data: